# Generated by Django 4.0.1 on 2022-01-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='departune_time',
            new_name='departure_time',
        ),
    ]
